### ISSUE TITLE
Panic when pulling from certain (closed) mensas

### ISSUE THREAD

**Issue by TheBadGod** [lukasmoellerch/mensa-cli#1]
```
panic: invalid h3 tag

goroutine 39 [running]:
github.com/lukasmoellerch/mensa-cli/internal/uzh.fetchMenuUzh.func1(0x81f9cd, 0xc0004226c0)
	/home/aaron/Projects/mensa-cli/internal/uzh/provider.go:277 +0x94b
github.com/PuerkitoBio/goquery.(*Selection).EachWithBreak(0xc000422450, 0xc000161e10)
	/home/aaron/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:21 +0x11f
github.com/lukasmoellerch/mensa-cli/internal/uzh.fetchMenuUzh({0x99781e, 0x5}, {0xc00002cfc0, 0xf}, {0xc00002cfe0, 0xd}, {0x996414, 0x0}, {0x99c8fa, 0xa})
	/home/aaron/Projects/mensa-cli/internal/uzh/provider.go:232 +0x53a
github.com/lukasmoellerch/mensa-cli/internal/uzh.(*Provider).FetchMenus.func1()
	/home/aaron/Projects/mensa-cli/internal/uzh/provider.go:79 +0x12b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/aaron/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/aaron/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

caused by [this](https://www.mensa.uzh.ch//en/menueplaene/lichthof-rondell/donnerstag.html) because there's no pipe in the h3 element. Fix by not panicking, but just warning (or returning false) when that happens.

**Comment by lukasmoellerch** [comment]
Thanks for the report - I'll take a look at it.
